# Generated by Django 5.2.9 on 2026-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrfile',
            name='docx_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrfile',
            name='pdf_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrfile',
            name='txt_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
