# Generated by Django 5.2.9 on 2026-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0002_ocrfile_docx_size_ocrfile_pdf_size_ocrfile_txt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrfile',
            name='processing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
