# Generated by Django 5.2.9 on 2026-01-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0004_remove_ocrfile_processing_time_ocrfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrfile',
            name='user',
        ),
    ]
