# Generated by Django 5.2.9 on 2026-01-16 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0006_ocrfile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('security_question_1', models.CharField(default='Which city would you like to live in?', editable=False, max_length=255)),
                ('security_answer_1', models.CharField(blank=True, max_length=255, null=True)),
                ('security_question_2', models.CharField(default='What is your favorite movie?', editable=False, max_length=255)),
                ('security_answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
