# Generated by Django 5.2.9 on 2026-01-16 06:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocrfile',
            unique_together={('user', 'file_name')},
        ),
    ]
